### ISSUE TITLE
Auroras not working after install of AVP Mod (No auroras, file missing)

### ISSUE THREAD

**Issue by RenZoc-FN** [themaster402/AstronomersVisualPack#22] opened 2021-06-10 14:56 UTC
A couple of files were missing but the one I really cared about was the auroras file ("aurora.dds") file was missing, I tried installing it from CKAN, It said everything was installed but It still did not have the files that I needed to have auroras. The Stars, clouds, and glows are working but not the clouds since the file are missing. I have also tried installing manually but it still did not work. can someone help?

By the way, I do not have any other visual mods, but I have EVE, Scatterer, and AVP.

**Comment by nefarias-bredd** [comment] 2021-12-19 20:11
Same issue here with v1.12 of the 8k textures. Installing v1.10 of 8k textures using ckan fixes.

Platform: Arch lts, running ckan using mono/KSP using Proton.

**Comment by themaster402** [comment] 2023-01-31 19:27
This was likely caused by playing on a version earlier than the latest major version (currently 1.12.x). The texture packs are all marked as compatible with "all versions", while the configs are marked only with the latest major version as I cannot confirm them working with previous ones. This will result in a mismatch between texture and config versions on CKAN.

**Closed as completed by themaster402** 2023-01-31 19:27 UTC
